apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki-ds
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: 'trace_id":"([a-f0-9]+)'
          datasourceUid: jaeger-ds
          url: '${__value.raw}'